orbs:
  react: thefrontside/react@0.2.0
  cypress: cypress-io/cypress@1
version: 2.1
workflows:
  push:
    jobs:
      - react/install
      - run: 'jest'
      - cypress/install:
          build: 'npm install'
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:3000'